### ISSUE TITLE
page 水印文字模糊

### ISSUE THREAD

**Issue by ikkz** [CleverLiurx/l-watermark#2]
看起来是 canvas 绘图共有的问题，能否优化一下呢 @CleverLiurx 

``` typescript
const watermark = WaterMark.page({
  containerEl: document.body,
  text: '预览模式',
  color: `${theme.semanticColors.bodyText}44`,
  fontSize: 16,
  vSpace: 35,
  cSpace: 35,
});
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/28710394/174486941-a8d1c9af-ac6e-483f-a066-f6c15ba62edd.png">

**Comment by CleverLiurx** [comment]
感谢，现在这版本的确模糊，现在我也经在升级了，下一版本就解决了（plan：将canvas缩放）

**Comment by CleverLiurx** [comment]
2.0.4已经解决

**Comment by CleverLiurx** [comment]
v2.0.4已经解决了

**Comment by ikkz** [comment]
已解决，感谢~
