### ISSUE TITLE
页面出现了多个水印

### ISSUE THREAD

**Issue by ikkz** [CleverLiurx/l-watermark#3]
使用中发现当手动改变水印元素的属性时会重新添加一个新的水印，原来的水印并没有移除掉，页面上就同时出现了多个水印叠加

https://github.com/CleverLiurx/l-watermark/blob/1f351cc4081e06bec9b34a0d2d3161e2166adc0f/src/guard-dom.ts#L53-L55

这里新添加元素之后 GuardDom.target 也没有和 PageWaterMark.watermakr 同步，导致 PageWaterMark.remove 只能移除掉最开始的那个水印元素

**Comment by CleverLiurx** [comment]
“手动改变水印元素的属性时会重新添加一个新的水印，原来的水印并没有移除掉”，出于安全考虑是这样的，我们小组成员进行过论证，不过下个版本会增加相关配置
